#+TITLE:
#+AUTHOR: 
# #+OPTIONS: toc:nil
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+DATE:

#+BEGIN_CENTER
SUNY POLYTECHNIC INSTITUTE

SCHOOL OF BUSINESS ADMINISTRATION
#+END_CENTER
#+BEGIN_CENTER
**FIN 420: FINANCIAL ANALYTICS**
#+END_CENTER
\\
**Instructor**: Matthew Brigida, Ph.D.
\\
**Office**: Donovan 1277 \\
**Office Hours**: Online in Brightspace \\
**Email**:  matthew.brigida@sunypoly.edu \\
**Class Location**: Brightspace \\
**Class Day/Time**: Online (Asynchronous) \\
#+begin_comment
**Office Hours**: Tuesdays 4:00--6:00pm
**Class Location**: Donovon 1157
**Class Day/Time**: Tuesdays 6:00--9:30pm
#+end_comment
\\
**Supplementary Texts/Materials**:
+ [[https://financial-education.github.io/][Financial Education]]
# + Advanced R, by Hadley Wickam (http://adv-r.had.co.nz/)
# + Python for Finance: Analyze Big Financial Data, Hilpisch,  ISBN-10: 9781491945285 
# + Quantitative Financial Analytics: The Path To Investment Profits, by Edward E Williams and John A Dobelman.  ISBN-13: 978-9813224254

* Description

An overview of analytical methods used in finance, and their applications.  Particular focus will be paid to methods for handling large data sets used in high-frequency trading, and machine learning and artificial intelligence methods applied to banking, investments, and energy markets.

** Course Learning Outcomes & Objectives

+ CLO 1. Technical Competence: Adept in applying analytics technology to solve institutional problems and enable effective financial decision making.
+ CLO 2. Analytical Problem Framing: Demonstrate individual capacity to evaluate and deploy analytical methods selected from a diverse portfolio of tools analyze and manage common financial decisions.
+ CLO 3. Strategic and Integrative Thinking: Understand the baseline resources available for analyzing and managing a firm’s financial performance. Including collecting data, processing information and evaluating and communicating outcomes with partners; differentiate between the accounting function as a preparer of data and information and the finance function as a user of information for decision making and the role of ethics in the process.
+ CLO 4. Leadership and Communication: Be capable of expressing key concepts and terms commonly used in financial analytics; by using effective written, oral and interpersonal communications to contribute to the financial performance of financial firms.

* Due Dates

#+begin_comment
The week 1 Colab notebook is due January 28.  Each Sunday thereafter the next Colab notebook is due.  For example, the week 2 Colab notebook is due February 5th.

It is important that you submit your assignment by the due date, particularly early in the semester.  By doing so we can identify any issues early.
#+end_comment

Summer courses are accelerated---you complete a full 14 week course in 8 weeks.  Therefore you will average more than 1 week [[https://financial-education.github.io/python_for_finance_outline/][in this outline]] every week of this course.  Assignments (weeks in the outline) 1 through 6 are due June 21.  Assignments 7 through 12 are due July 19.  

* How to Submit Your Colab Notebook

To submit your notebook simply paste the link to your completed notebook in the D2L/Brightspace dropbox.  There are two additional key points:

1.  Make sure your Colab notebook sharing setting is set to 'viewable by anyone on the web'.  I can't grade your notebook if I can't see it.
2.  If you open a notebook and modify it, it doesn't automatically create a new URL.  So if you copy the URL and submit it, you are giving me a link to /my own notebook/ with none of your changes. So once you modify a notebook that you want to submit, save the Colab notebook to Google Drive to create a unique URL.

* Course Outline

[[https://financial-education.github.io/python_for_finance_outline/][See the weekly Colab Notebook links and videos in the course outline.]]

* Exams

There are no exams scheduled, however a final exam may be added at the instructor's discretion. 

* Attendance/Participation

#+begin_comment
You will receive participation points for using the discussion board to ask and answer questions.  Sending me emails asking non-personal course related questions (against the course communication policy) will cause you to lose participation points.
#+end_comment

Throughout the semester I will take attendance, may give unannounced quizzes, and otherwise evaluate your participation.  Failure to attend class and participate will reduce your participation score.

* Grading

#+BEGIN_CENTER

| Item                     | Points |
|--------------------------+--------|
| Assignments              |     90 |
| Attendance/Participation |     10 |
|--------------------------+--------|
| Total Points             |    100 |
|--------------------------+--------|
#+END_CENTER


#+begin_comment
# #+BEGIN_CENTER
Final grades will be assigned according to the A+, A, A-, etc scale.
# #+END_CENTER
#+end_comment


- 90 - 100 A
- 80 - 89.9 B
- 70 - 79.9 C
- 60 - 69.9 D
- $<$ 60 F

#+BEGIN_QUOTE
+/- grades may be assigned at the instructors discretion.
#+END_QUOTE

** An Important Note on Grading

#+BEGIN_QUOTE
There is no special consideration if you need a certain grade in this course to graduate.  **If you require a certain grade in this class to graduate it is your responsibility to earn that grade.** Specifically if you receive a `D` in this course I will not allow you to do extra assignments after the course is complete in exchange for a higher grade. 
#+END_QUOTE

* How To Ask Questions

The more information you provide, the more likely I will be able to answer your question.  If you simply say "I got an error" then you should not expect anyone to be able to help.  At the very least provide the text of the error.

[[https://stackoverflow.com/help/how-to-ask][See this post.]]  

* Email Communication

Questions about course material should be asked in class.  Email should only be used for personal matters.  When sending an email, be sure to put the course in the subject line (FIN 420). 

#+begin_comment
Questions about course material should be posted to the most relevant discussion board.  Email should only be used for personal matters.  When sending an email, be sure to put the course in the subject line (FIN 420). 
#+end_comment

* Guidelines and Accommodations

Academic Integrity Policy Students Enrolled in this course are required to understand and fully comply with all aspects of the Academic Integrity Policy as described in the SUNY Polytechnic Institute Handbook (available at:  https://sunypoly.edu/pdf/student_handbook.pdf )

** Accommodations for Students with Disabilities

#+begin_quote
In compliance with the Americans with Disabilities Act of 1990 and Section 504 of the Rehabilitation Act, SUNY Polytechnic Institute is committed to ensuring comprehensive educational access and accommodations for all registered students seeking access to meet course requirements and fully participate in programs and activities.  Students with documented disabilities or medical conditions are encouraged to request these services by registering with the Office of Disability Services. Please request accommodations early in the semester, or as soon as you become registered with Disability Services, so that we have adequate time to arrange your approved academic accommodation/s.  Once Disability Services creates your accommodation plan, it is your responsibility to provide me a copy of the accommodation plan.

If you experience any access concerns that may require the need for adaptive or alternate format/presentation of materials, reach out to me or Disability Services right away. 

For information related to these services or to schedule an appointment, please contact the Office of Disability Services using the information provided below.  The Office of Disability Services can accommodate virtual meeting requests.  The website has helpful information, and the link can be found here: https://sunypoly.edu/student-life/diversity-equity-inclusion/disabilities-services/contact-us.html
#+end_quote

* Bonus Project Ideas

None of these are necessary, and should not take the place of any assigned work.

- [[https://colab.research.google.com/drive/1OtpEsx3RyoishcmKX4Q0a_DZ2XHM3rje?usp=sharing][Option Greeks in Margrabe]]
- The Pairs Trade
- Classify Failed Banks with a Deep Neural Network
- Algorithm Identification in High-Frequency Markets
- Determining the Effect of Bank Capital Adequacy Requirements
- Bank Stress Testing
- Machine Learning in Portfolio Construction
- Constructing an Artificial Intelligence Investment Advisor

