#+TITLE:FIN 420: Financial Analytics
#+AUTHOR: SYLLABUS
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#  #+OPTIONS: toc:nil
#+DATE:


#+BEGIN_CENTER
SUNY POLYTECHNIC INSTITUTE

SCHOOL OF BUSINESS ADMINISTRATION
#+END_CENTER
\\
\\
**Instructor**: Matthew Brigida, Ph.D.\\
\\
**Office**: Donovan 1277\\
\\
**Office Hours**: Two hours before each class.\\
\\
**Email**:  matthew.brigida@sunypoly.edu\\
\\
**Class Location**: Online Asynchronous\\
\\
#+begin_comment
**Class Day/Time**: Wednesdays 6:00--9:30pm\\
#+end_comment
\\
**Supplementary Texts/Materials**:
+ Advanced R, by Hadley Wickam (http://adv-r.had.co.nz/)
+ [[https://financial-education.github.io/][Financial Education]]
# + Python for Finance: Analyze Big Financial Data, Hilpisch,  ISBN-10: 9781491945285 
# + Quantitative Financial Analytics: The Path To Investment Profits, by Edward E Williams and John A Dobelman.  ISBN-13: 978-9813224254

* Description

An overview of analytical methods used in finance, and their applications.  Particular focus will be paid to methods for handling large data sets used in high-frequency trading, and machine learning and artificial intelligence methods applied to banking, investments, and energy markets.

#+begin_comment
Overview

-  This course will present the fundamentals of managerial finance as a vital part of the complete business ecosystem. Importance is placed on becoming familiar with the rudimentary tools and techniques that act as the basis for all further study and function of finance.

-  Emphasis is also placed on exploring the human, technological, and environmental impacts on financial decision making and the societal variables that facilitate positive (financial and social) outcomes.

-  Attention to current events and linkage between financial markets and corporate decision-making and vis-a-vis is discussed.

-  Introduction to the role of the change agent and changing technology in financial analysis and financial decision-making processes.
#+end_comment

** Course Learning Outcomes & Objectives

+ CLO 1. Technical Competence: Adept in applying analytics technology to solve institutional problems and enable effective financial decision making.
+ CLO 2. Analytical Problem Framing: Demonstrate individual capacity to evaluate and deploy analytical methods selected from a diverse portfolio of tools analyze and manage common financial decisions.
+ CLO 3. Strategic and Integrative Thinking: Understand the baseline resources available for analyzing and managing a firm’s financial performance. Including collecting data, processing information and evaluating and communicating outcomes with partners; differentiate between the accounting function as a preparer of data and information and the finance function as a user of information for decision making and the role of ethics in the process.
+ CLO 4. Leadership and Communication: Be capable of expressing key concepts and terms commonly used in financial analytics; by using effective written, oral and interpersonal communications to contribute to the financial performance of financial firms.

* Course Outline

** Week 0

- Course Overview:  
  + What we will cover in the course.  
  + The use of Python in finance.

- Python Relative to other tools.
  + Excel
  + Other Programming Languages
  + Comparison with R
  + Using Javascript for Visualization

** Week 1

[[https://colab.research.google.com/drive/1f2JRrZsZ029JNiPnP_GNiVsyi-e6MXO5][Colab Notebook]]

- You are on a Linux Server
-  Interacting with Python
  + Google's Colab and Jupyter
    - Introduction to markdown
    - Sharing notebooks
- Creating Functions and Time-Value-of-Money calculations
- Basic control flow
  + The importance of indentation

** Week 2

[[https://colab.research.google.com/drive/12QKdTc3ulsEQ2cAdmbhq5RkTx9oB1YZ_][Colab Notebook]]

The Python ecosystem.

-  An Introduction to Useful Packages:
  + [[https://pandas.pydata.org/][Pandas]]
  + [[https://numpy.org/][Numpy]]
  + Scipy and Scikit Learn
  + Pytorch
  + Tensorflow and Keras 

- Finding Packages
  + pip

- Python Packages
  + Extending the core language
  + Our most used packages.
  + Installing and Loading.
  + How to call methods/functions from a package.

-  Python Classes and Object Orientation
  + What is a Class
  + Function vs Method:  methods are functions attached to a class

** Week 3

[[https://colab.research.google.com/drive/1KLqsQWbXHYSruQXBAJ1QamsxV9FLDN_R][Colab Notebook]]

- An intro to Pandas
- Reading csv and excel files.
  + Locally and over the web.
- Inspecting the objects
- Determining dataframe size and the column types.
- Adding new columns

** Week 4

[[https://colab.research.google.com/drive/16UVjO2PEQUN5b1JoI__JYfj7K_aMuom7#scrollTo=nBbjWR1JYksh][Colab Notebook]]

** Week 5

[[https://colab.research.google.com/drive/18axbgTGt66R7fXa3tsiErQMoyb8m-AJD][Colab Notebook]]

** Week 6

[[https://colab.research.google.com/drive/1TWjqlgTp1Fyyy_ykp48LBVFWjRqtBwzo][Colab Notebook]]

SQL from Python

** Week 7

[[https://colab.research.google.com/drive/16h1ykVWbb5fL-xRgOrYmYe9SqfrSin1x#scrollTo=4cmbxkCjM1fH][Colab Notebook]]

- An introduction to Application Programming Interfaces (APIs) and online
  data
  + Example: Coinbase API
  + Example: Interactive Brokers API
  + EIA API.
- Connecting to databases.

** Week 8

[[https://colab.research.google.com/drive/1GGXpVBhSIypRslVcjWB5TYcexeRxZlyY][Colab Notebook]]

-  An overview of scipy and basic statistics in Python.
  + Extracting coefficients from an estimated regression model.

** Week 9

[[https://colab.research.google.com/drive/1u4BUOasPaIVfe8-rD73QXlXmt5EMIMxK][Colab Notebook]]

** Week 10

The previous sections have used data available online through APIs and simple files.  Commonly the financial analyst will have to query relational (SQL) databases.  In this section we'll cover the basics of connecting to a SQL database in Python, and executing SQL queries.  The resulting data table will, of course, be imported back into Python.

-  Good website to learn SQL (MySQL): [[https://www.db-fiddle.com/][db-fiddle]]

# A quick project using SQL.  Is there an online SQL database we can query?  Should we just put the FDIC one online?


** Week 11

[[https://colab.research.google.com/drive/1CQ00H_duTY2lhiwzJ041JTPD6BGBdk5y#scrollTo=Z5RfT4TNucfe][Colab Notebook]]

- Visualization:
  + Matplotlib
  + Seaborn
  + Plotly
  + ggplot (using plotnine library)
- Interactive Web Apps via Plotly's Dash

** Week 12

- The Integrated Development Environment (IDE)
  + What does an IDE provide?
    - Code Completion
    - Linter
  + Git/Github and IDE Integration

** Week 13

- Git/Github and IDE Integration
  + Why use version control?
    - Collaborate with others more easily.
    - Show others your work.

- [[https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb][Github from Colab]]

- Virtual Environments
  +  Ensuring compatible python and package versions.
  +  Anaconda Python

** Bonus Project: The Pairs Trade
** Bonus Project: Classify Failed Banks with a Deep Neural Network
** Algorithm Identification in High-Frequency Markets
** Determining the Effect of Bank Capital Adequacy Requirements
** Bank Stress Testing
** Machine Learning in Portfolio Construction
** Constructing an Artificial Intelligence Investment Advisor

* Exams

There will be two brief exams---a midterm and a final.

* Attendance/Participation

Throughout the semester I will take attendance, give unanounced quizzes, and otherwise evaluate your participation.  Failure to attend class and participate will reduce your participation score, unless your absence is due to a **verifiable** medical or family emergency.  In such a case you must provide documentation.

* Grading

#+BEGIN_CENTER

| Item                     | Points |
|--------------------------+--------|
| Assignments              |     80 |
| Attendance/Participation |     20 |
|--------------------------+--------|
| Total Points             |    100 |
|--------------------------+--------|
#+END_CENTER
#+begin_comment
| Midterm                  |     10 |
| Final Exam               |     10 |
#+end_comment
# #+BEGIN_CENTER
Final grades will be assigned according to the A+, A, A-, etc scale.
# #+END_CENTER

#+begin_comment
- 90 - 100 A
- 80 - 89.9 B
- 70 - 79.9 C
- 60 - 69.9 D
- $<$ 60 F

#+BEGIN_QUOTE
+/- grades may be assigned at the instructors discretion.
#+END_QUOTE

#+end_comment


** An Important Note on Grading

#+BEGIN_QUOTE
There is no special consideration if you need a certain grade in this course to graduate.  **If you require a certain grade in this class to graduate it is your responsibility to earn that grade.** Specifically if you receive a `D` in this course I will not allow you to do extra assignments after the course is complete in exchange for a higher grade. 
#+END_QUOTE

* How To Ask Questions

[[https://stackoverflow.com/help/how-to-ask][See this post.]]  

* Email Communication

Questions about course material should be posted to the most relevant discussion board.  Email should only be used for personal matters.  When sending an email, be sure to put the course in the subject line (FIN 420). 

* Guidelines and Accommodations

Academic Integrity Policy Students Enrolled in this course are required to understand and fully comply with all aspects of the Academic Integrity Policy as described in the SUNY Polytechnic Institute Handbook (available at:  https://sunypoly.edu/pdf/student_handbook.pdf )

** Accommodations for Students with Disabilities

#+begin_quote
In compliance with the Americans with Disabilities Act of 1990 and Section 504 of the Rehabilitation Act, SUNY Polytechnic Institute is committed to ensuring comprehensive educational access and accommodations for all registered students seeking access to meet course requirements and fully participate in programs and activities.  Students with documented disabilities or medical conditions are encouraged to request these services by registering with the Office of Disability Services. Please request accommodations early in the semester, or as soon as you become registered with Disability Services, so that we have adequate time to arrange your approved academic accommodation/s.  Once Disability Services creates your accommodation plan, it is your responsibility to provide me a copy of the accommodation plan.

If you experience any access concerns that may require the need for adaptive or alternate format/presentation of materials, reach out to me or Disability Services right away. 

For information related to these services or to schedule an appointment, please contact the Office of Disability Services using the information provided below.  The Office of Disability Services can accommodate virtual meeting requests.  The website has helpful information, and the link can be found here: https://sunypoly.edu/student-life/diversity-equity-inclusion/disabilities-services/contact-us.html
#+end_quote
